### ISSUE TITLE
Fixing segmentation tool in SimVascular version with new Externals

### ISSUE THREAD

**Issue by lucapegolotti** [SimVascular/SimVascular#1033]
**Describe the bug**
In the new SimVascular version using the new External versions, the segmentation tool needs to be fixed. There are two main issues:

- The method that used to handle the transition to the default 4 window view to the 3 window view (`SetAll2DLeft3DRightLayout()`, see          [here](https://github.com/lucapegolotti/SimVascular/blob/6eb5a30faa4ddc4b849e305818c0465504c804e6/Code/Source/sv4gui/Modules/QtWidgets/sv4gui_ResliceSlider.cxx#L200)) we use for segmentation has been removed from MITK. I've managed to obtain a similar behavior using ALL_2D_LEFT_3D_RIGHT method (see [here](https://github.com/lucapegolotti/SimVascular/blob/6eb5a30faa4ddc4b849e305818c0465504c804e6/Code/Source/sv4gui/Modules/QtWidgets/sv4gui_ResliceSlider.cxx#L202)), but now we have three views on the left and I haven't figured out how to get rid of one. @fkong7 might have also spent some time trying to fix this.
- The method `SetInputWorldGeometry3D` doesn't exist anymore, and we used that to change the views on the left to the slicing plane. [This](https://github.com/lucapegolotti/SimVascular/blob/6eb5a30faa4ddc4b849e305818c0465504c804e6/Code/Source/sv4gui/Modules/Segmentation/sv4gui_SegmentationUtils.cxx#L338) is how we used to create a sliced geometry, and [this](https://github.com/SimVascular/SimVascular/blob/edd1fc7c26cf9550594a7362d66bb5d0fadda4d9/Code/Source/sv4gui/Modules/QtWidgets/sv4gui_ResliceSlider.cxx#L192) is how we used to assign the geometry to the view.

**To Reproduce**
1.` git clone https://github.com/lucapegolotti/SimVascular.git ; cd SimVascular`
2. `git checkout updateExternals`
3. `bash compile.sh`
4. Load a project in SimVascular, and open one of the segmentations.

**Expected behavior**
We should be able to reproduce the old behavior of SimVascular as closely as possible

**Screenshots**
Below is how the segmentation tool looks like now:
![segmentation_tool](https://github.com/SimVascular/SimVascular/assets/13286853/c7912001-ea2d-409c-bdd8-52fe8ffe3f7e)

This is how it used to look.
![segmentation_tool_real](https://github.com/SimVascular/SimVascular/assets/13286853/c3240029-3268-4174-8d69-64cb032cfa1a)

**Desktop (please complete the following information):**
 - OS: Ubuntu20

**Comment by ktbolt** [comment]
I've modified `sv4guiSegmentationUtils::CreateSlicedGeometry()` to create and return a `mitk::ProportionalTimeGeometry` object and use it in `sv4guiResliceSlider::updateReslice()` as
```
   intensityController->SetInputWorldTimeGeometry(currentSlicedGeometry);
```

I made these changes to the current SimVascular source and they worked, slicing in the Segmentation Tool looked fine.

I made the same changes to the  `updateExternals` SimVascular source but got a segmentation fault in `sv4guiSegmentationUtils::CreateSlicedGeometry()` when calling ` mitk::ProportionalTimeGeometry::Initialize()`
```
    auto prop_time_geom = mitk::ProportionalTimeGeometry::New();

    prop_time_geom->Initialize(slicedGeo3D, 1);
```

Investigating I found that `slicedGeo3D->Clone()` is failing in `mitk::SlicedGeometry3D::SetPlaneGeometry()` because the `SlicedGeometry3D` copy constructor is not allocating its `m_PlaneGeometries` member data (I think).


@lucapegolotti How can I update the MITK source we are using for the externals. 

I was also wondering if you compiling MITK with DEBUG, would be good to see any asserts that fail.

**Comment by lucapegolotti** [comment]
@ktbolt to update the MITK source files, we would need to create a patch and add it to [this script](https://github.com/lucapegolotti/SVExternals/blob/main/scripts/build_mitk.sh) before compiling it.

The current version of MITK is Release. I could compile one in Debug before you move on further to make sure that the problem is what you mentioned. Let me know if I should do it and I can have it uploaded by the end of the day.

**Comment by ktbolt** [comment]
@lucapegolotti Please compile a new MITK external with DEBUG so we can catch any problems that it might be checking for.

I would also like to add `m_PlaneGeometries.assign(other.m_Slices, gnull);`

after line 43 in MITK/Modules/Core/src/DataManagement/mitkSlicedGeometry3D.cpp



mitk::SlicedGeometry3D::SlicedGeometry3D(const SlicedGeometry3D &other)
  : Superclass(other),
    m_EvenlySpaced(other.m_EvenlySpaced),
    m_Slices(other.m_Slices),
    m_ReferenceGeometry(other.m_ReferenceGeometry),
    m_SliceNavigationController(other.m_SliceNavigationController)
{
  m_DirectionVector.Fill(0);
  SetSpacing(other.GetSpacing());
  SetDirectionVector(other.GetDirectionVector());
  `m_PlaneGeometries.assign(other.m_Slices, gnull);`

  if (m_EvenlySpaced)
  {
    assert(!other.m_PlaneGeometries.empty() && "This may happen when you use one of the old Initialize methods, which had a bool parameter that is implicitly casted to the number of slices now.");
    PlaneGeometry::Pointer geometry = other.m_PlaneGeometries[0]->Clone();
    assert(geometry.IsNotNull());
.
.

**Comment by lucapegolotti** [comment]
@ktbolt I applied the patch and recompiled MITK. It will be downloaded automatically if you recompile SV.

**Comment by ktbolt** [comment]
@lucapegolotti Thanks for the new externals!

 I ran SV with the new externals, didn't see any assert messages and it still fails in `mitk::SlicedGeometry3D::SetPlaneGeometry()`.

I would like to add some checks and things to the MITK source. Can you tell me how to setup a build system on my Ubuntu 20 VM?

**Comment by lucapegolotti** [comment]
@ktbolt You can clone https://github.com/lucapegolotti/SVExternals and launch the `build_all.sh` script. I haven't used that script lately, because the actions use the workflows in the `.github` repository, but I think it should work. Hopefully your VM has all the required packages. Otherwise, you could use the [container I made](https://hub.docker.com/repository/docker/lucapegolotti/ubuntu20-svexternals/general) which for sure has all the required dependencies, but you cannot launch the GUI from there. 

I am not sure how to use the libraries after you have built them. My workaround has always been to put them in `/home/www-shared/html/downloads/public/simvascular/externals/2022.10/linux/ubuntu/20.04/gnu/7.5/x64/release/2022.10.13` on tetra, which is the location where they are automagically downloaded from. If you know of a better way to use a local installation though that would be certainly easier.

**Comment by ktbolt** [comment]
@lucapegolotti How much disk space is required to build the externals?

**Comment by lucapegolotti** [comment]
@ktbolt I am not sure, but I can change the build scripts to delete the build folders after every library is installed. The SVExternals folder on my workstation is 48 GB, but there's some duplicated stuff. How much memory does your VM have?

**Comment by ktbolt** [comment]
@lucapegolotti My VM has 30GB. I will make a larger one. 

It would also be good to send me all of the apt-get commands you use to build the externals so I can reproduce this on my VM.

**Comment by lucapegolotti** [comment]
@ktbolt this should do it:

```
sudo apt-get update
sudo apt-get install -y \
libfontconfig1-dev \
libfreetype6-dev \
libx11-dev \
libx11-xcb-dev \
libxext-dev \
libxfixes-dev \
libxi-dev \
libxrender-dev \
libxcb1-dev \
libxcb-glx0-dev \
libxcb-keysyms1-dev \
libxcb-image0-dev \
libxcb-shm0-dev \
libxcb-icccm4-dev \
libxcb-sync0-dev \
libxcb-xfixes0-dev \
libxcb-shape0-dev \
libxcb-randr0-dev \
libxcb-render-util0-dev \
libxkbcommon-dev \
libxkbcommon-x11-dev \
gcc \
make \
automake \
git \
gperf \
bison \
nodejs \
libxt-dev \
libtiff4-dev \
file \
rsync \
llvm \
libpcre3 \
libpcre3-dev \
build-essential \
libgl1-mesa-dev \
libglu1-mesa-dev \
libxcb-render0-dev \
libdbus-1-dev \
libnss3-dev \
byacc \
libxi-dev \
libxcomposite-dev \
libxcursor-dev \
libxtst-dev \
libatspi2.0-dev \
libxcb-util0-dev \
libxcb-xinerama0-dev \
libxcb-xkb-dev \
libxcomposite-dev \
libdrm-dev \
libxdamage-dev \
libxrandr-dev \
libssl-dev \
python2
```

Then you also need to `sudo ln -s /usr/bin/python2.7 /usr/bin/python` because QtWebEngine requires Python2. I should have included everything you need but please let me know if you have any issues because there's a high chance that I already had to fix those in the past.

**Comment by ktbolt** [comment]
@lucapegolotti Thanks, I'll give it a go!

**Comment by ktbolt** [comment]
@lucapegolotti Running the `build_all.sh` failed with
```
qt-everywhere-opensource-sr 100%[===========================================>] 629.15M  5.26MB/s    in 2m 3s   

2023-09-18 13:06:50 (5.10 MB/s) - ‘qt-everywhere-opensource-src-5.15.10.tar.xz.2’ saved [659711492/659711492]

xz: (stdin): Unexpected end of input
tar: Unexpected EOF in archive
```

**Comment by lucapegolotti** [comment]
@ktbolt I think you might have multiple versions of `qt-everywhere-opensource-src-5.15.10.tar.xz` in your `src` folder. By default, the script attempts to untar `qt-everywhere-opensource-src-5.15.10.tar.xz`, but yours is probably incomplete. In the case of the error, you successfully untarred `qt-everywhere-opensource-src-5.15.10.tar.xz.2`. You could try deleting those tar files from `src` and relaunching the script.

**Comment by ktbolt** [comment]
@lucapegolotti That seems to be working, thanks.

**Comment by ktbolt** [comment]
@lucapegolotti I've tried running the build in your container without success
- Ubuntu 20 VM - Freezes the VM and also the Windows laptop it is running on
- MacOS Ventura/M2 - Build fails compiling Qt in `sub-gn_run-pro-make`
- MacOS Catalina/Intel - Build has run for three days compiling Qt but appears to be stuck calling python2

I could not get the build to work in a Ubuntu 20 VM without a container, will look at that again.

**Comment by lucapegolotti** [comment]
@ktbolt I am not surprised the container fails on the M2 because I think that images built for x86 cannot be run on arm. I am assuming that the failure in the VM is due to insufficient allocated resources (probably RAM?) since the compilation of Qt is pretty expensive. I am surprised that the build took so long on the intel Mac and that it got stuck because in that case I think the performance should be near native. I am available to meet today if you want to have a look at it together.

**Comment by lucapegolotti** [comment]
@ktbolt I fixed a bug in the MITK script that prevented the patch you asked me to make from being applied. Could you please recompile SimVascular on Ubuntu 20 (it will download the new library versions) and check if, by any chance, that fixes the issue you were having?

**Comment by ktbolt** [comment]
@lucapegolotti I recompiled and tested, crashed in the same place.

**Comment by ktbolt** [comment]
@lucapegolotti Maybe add some print statements to `mitk::SlicedGeometry3D::SetPlaneGeometry()` ?

**Comment by ktbolt** [comment]
I've am now able to build externals for Ubuntu 20, added some debugging statements to the `mitk::SlicedGeometry3D` class.

However, SV fails when building with the new externals 
```
- Search paths for MITKConfig.cmake simvascular-new-externals/SimVascular/Code/CMake;
-- MITK
-- 2022.10;REQUIRED
CMake Error at CMake/FindMITK.cmake:251 (message):
  MITK_LIBS_MISSING:
  CppMicroServices;mbilog;MitkAlgorithmsExt;MitkAppUtil;MitkCore;MitkContourModel;MitkDataTypesExt;MitkImageDenoising;MitkMapperExt;MitkQtWidgets;MitkQtWidgetsExt;MitkSceneSerialization;MitkSegmentation;MitkSegmentationUI;MitkSurfaceInterpolation;PythonQt;MitkMultilabel
Call Stack (most recent call first):
  CMake/SimVascularMacros.cmake:144 (find_package)
  CMake/Externals/MITK.cmake:68 (simvascular_external)
  CMake/SimVascularExternals.cmake:37 (include)
  CMakeLists.txt:107 (include)
```
The `CppMicroServices` library used to be located in `svExternals/bin/mitk-2018.04.2/lib` but in is now located in `svExternals/bin/mitk-2018.04.2/bin`.

**Comment by lucapegolotti** [comment]
@ktbolt in the `scripts` folder, there's a script called post-install-mitk.sh. Could you try to run it before you zip the externals and move them to tetralogy? I forgot to add that script to the `build_all.sh` main script because the github workflows don't use it. I will update `build_all.sh`

**Comment by ktbolt** [comment]
@lucapegolotti What directory do I run that `post-install-mitk.sh` from? 

Do I need to add `source env_variable.sh` to that script?

**Comment by lucapegolotti** [comment]
@ktbolt, this is the sequence in the github workflows:
```
source env_variables.sh
source scripts/build_mitk.sh
source scripts/post-install-mitk.sh
```
You can skip `build_mitk.sh `since you already built it.

**Comment by ktbolt** [comment]
That worked, can now build SV with new externals.

**Comment by ktbolt** [comment]
@lucapegolotti I did a new build using the latest https://github.com/lucapegolotti/SVExternals. SV build now fails with
```
- Search paths for tinyxml2Config.cmake: /home/davep/tmp/simvascular-new-externals/SimVascular/Code/CMake;
-- tinyxml2
-- REQUIRED
CMake Error at CMake/SimVascularMacros.cmake:144 (find_package):
  By not providing "Findtinyxml2.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "tinyxml2",
  but CMake did not find one.

  Could not find a package configuration file provided by "tinyxml2" with any
  of the following names:

    tinyxml2Config.cmake
    tinyxml2-config.cmake

  Add the installation prefix of "tinyxml2" to CMAKE_PREFIX_PATH or set
  "tinyxml2_DIR" to a directory containing one of the above files.  If
  "tinyxml2" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMake/Externals/TINYXML2.cmake:74 (simvascular_external)
  CMake/SimVascularExternals.cmake:37 (include)
  CMakeLists.txt:107 (include)
```

**Comment by ktbolt** [comment]
The debugging statements I added to `SlicedGeometry3D` show that the `m_PlaneGeometries` vector size is allocated for 616 slices and that a segfault occurs when storing into its 0-index. 

The back trace of the SV core file shows the segfault occures in itk smart pointer code
```
#0  0x00007f6ec040a289 in itk::SmartPointer<mitk::PlaneGeometry>::Register (this=0x7fffa05ded28)
    at /home/davep/SVExternals/install/itk-5.2.1/include/ITK-5.2/itkSmartPointer.h:205
#1  0x00007f6ec0408f44 in itk::SmartPointer<mitk::PlaneGeometry>::SmartPointer (this=0x7fffa05ded28, p=0x5558fe2464c0)
    at /home/davep/SVExternals/install/itk-5.2.1/include/ITK-5.2/itkSmartPointer.h:99
#2  0x00007f6ec11821ea in mitk::SlicedGeometry3D::SetPlaneGeometry (this=0x5558f725e390, geometry2D=0x5558fe2464c0, s=0)
    at /home/davep/SVExternals/src/MITK-2022.10/Modules/Core/src/DataManagement/mitkSlicedGeometry3D.cpp:145
#3  0x00007f6ec118188c in mitk::SlicedGeometry3D::SlicedGeometry3D (this=0x5558f725e390, other=...)
    at /home/davep/SVExternals/src/MITK-2022.10/Modules/Core/src/DataManagement/mitkSlicedGeometry3D.cpp:74
#4  0x00007f6ec1184a03 in mitk::SlicedGeometry3D::InternalClone (this=0x5558f6e6f110)
    at /home/davep/SVExternals/src/MITK-2022.10/Modules/Core/src/DataManagement/mitkSlicedGeometry3D.cpp:620
#5  0x00007f6eb37164cd in sv4guiSegmentationUtils::CreateSlicedGeometry(std::vector<sv4guiSpline::sv4guiSplinePoint, std::allocator<sv4guiSpline::sv4guiSplinePoint> >, mitk::BaseData*, double, bool) ()
```

I'm not sure what's going here, perhaps the reference geometry set for the slice plane is corrupted or has gone out of scope.

**Comment by lucapegolotti** [comment]
@ktbolt Could you push your fork somewhere so that I can also have a look at what's going on?

**Comment by ktbolt** [comment]
I've created  https://github.com/ktbolt/SimVascular/tree/Fixing-segmentation-new-Externals_1033 containing the changes using `mitk::ProportionalTimeGeometry`
```
	modified:   Code/Source/sv4gui/Modules/QtWidgets/sv4gui_ResliceSlider.cxx
	modified:   Code/Source/sv4gui/Modules/QtWidgets/sv4gui_ResliceSlider.h
	modified:   Code/Source/sv4gui/Modules/Segmentation/sv4gui_SegmentationUtils.cxx
	modified:   Code/Source/sv4gui/Modules/Segmentation/sv4gui_SegmentationUtils.h
```

**Comment by lucapegolotti** [comment]
@ktbolt that version of SimVascular is not related to my fork. Are you trying to make it work with the old versions of the externals and then moving to the new ones?

**Comment by ktbolt** [comment]
@lucapegolotti The changes I made in my branch are the same changes I made in your fork, just copied the files over.

**Comment by ktbolt** [comment]
I tried building the externals with an earlier `ITK version (5.1.2)` but SV still crashed.

I also tried using `valgrind` to detect memory faults but `valgrind` itself crashed, SV was just too much for it, I can relate ...

**Comment by lucapegolotti** [comment]
@ktbolt did you also try with the previous version of ITK we were using in SimVascular? I think the previous version was 4.13.2

**Comment by ktbolt** [comment]
I tried ITK 4.13.2 but got a million errors with all of the other packages and OpenGL. There is also VTK 8 vs VTK 9 issues.

**Comment by lucapegolotti** [comment]
Ok, it was a long shot. I wonder if there's an easy way to check if I introduced any bugs when I fixed the many compilation errors I found when upgrading VTK from 8 to 9. In particular, I had to fix some pointer issues:
https://github.com/SimVascular/SimVascular/commit/5a50ca41822438ced6645d8b0708e0f1505a952b

@ktbolt do you see anything strange in this commit?

**Comment by ktbolt** [comment]
@lucapegolotti This commit seems to be just changes to vmtk which is not called I think. 

Btw, you should just use `const vtkIdType *pts` and not allocate memory using `const vtkIdType *pts = new vtkIdType;` because `pts` will just be overwritten in the `GetCellPoints(cells[i],npts,pts)` call.

**Comment by ktbolt** [comment]
@lucapegolotti Finally getting back to this!

**Comment by ktbolt** [comment]
I've updated my Mac (Intel) to Monterey and have built SV using the new externals. SV seems to run OK but segfaults when I close it. 

I am not able to build on Mac Silicon yet, can't get Qt to build QtWebEngine.

**Comment by lucapegolotti** [comment]
@ktbolt interesting. I did not notice the segfault when closing the window.  Did you manage to fix the segmentation tool as well?

**Comment by ktbolt** [comment]
@lucapegolotti I have not fixed the segmentation tool, wanted to first get SV to build on a Mac so I could experiment a bit and try to understand the code in `sv4guiResliceSlider::updateReslice`, lots of changes there. 

What are the dependencies needed to get Qt to build with `QtWebEngine`? I looked on the Qt forum and installed all of the packages they listed but no dice.

**Comment by lucapegolotti** [comment]
@ktbolt you can find the list of all the dependencies needed to build all the externals [here](https://simvascular.github.io/svExternals/containers.html) but they are not divided into packages that need them. A list of dependencies for Qt5 is [here](https://doc.qt.io/qt-5/linux-requirements.html). There’s also a link for `QtWebEngine`. The tricky part about `QtWebEngine` is that if the dependencies are not satisfied Qt is silent about it. It just throws some warnings after configuration.

**Comment by ktbolt** [comment]
I am getting the same segfault behavior on Mac/Monterey/Intel using the downloaded externals.

I added a function to SV `main()` to mimic the `SlicedGeometry3D ` calls and still get a segfault so it appears this is maybe not a memory corruption problem somewhere in SV.

**Comment by ktbolt** [comment]
I am trying to build MITK and and example that use it to test some ideas. This is truly a nightmare trying to get MITK to build on a Mac and then use it in a program.

**Comment by lucapegolotti** [comment]
@ktbolt dis you try to use [this script](https://github.com/SimVascular/svExternals/blob/main/scripts/build_mitk.sh) to build MITK on the Mac? It used to work on Mac virtual machines.

**Comment by ktbolt** [comment]
@lucapegolotti I was trying to build MITK from source using installed packages, finally got it to build from the github source. 

I am now trying to build a small program that uses MITK from the svExternals build but CMake fails with
```
 Could NOT find Python3 (missing: Python3_NumPy_INCLUDE_DIRS NumPy) (found version "3.12.2")
```

**Comment by lucapegolotti** [comment]
@ktbolt Not sure if this is going to help, but could you please add the environment variables I had to add to build SimVascular with the new externals? https://github.com/lucapegolotti/SimVascular/blob/updateExternals/compile.sh

I am not sure if the LD_LIBRARY_PATH step solved an issue at compile time, linking or runtime.

**Comment by lucapegolotti** [comment]
Probably this will not help because your error is an include error but I needed to add LD_LIBRARY_PATH for linking. Is 3.12.2 your system Python?

**Comment by ktbolt** [comment]
Python 3.12.2 is the system Python. 

In the build  CMakeCache.txt file I see
```
PYTHON_EXECUTABLE:FILEPATH=/home/svExternals/install/python-3.9.10/bin/python
PYTHON_INCLUDE_DIR:PATH=/home/svExternals/install/python-3.9.10/include/python3.9
PYTHON_INCLUDE_DIR2:PATH=
PYTHON_LIBRARY:FILEPATH=/home/svExternals/install/python-3.9.10/lib/libpython3.9.dylib
```

I tried setting `LD_LIBRARY_PATH` but that did not work.

**Comment by ktbolt** [comment]
I've added the CMake `find_package(Python3 COMPONENTS Interpreter Development)` command without the `PATHS  /home/svExternals/install/python-3.9.10` and my test program now compiles.

The `find_package(Python3)` finds the system Python3 but then MITK finds (I think) the svExternals Python, seen in CMakeCache.txt
```
PYTHON_EXECUTABLE:FILEPATH=/Users//svExternals/install/python-3.9.10/bin/python
PYTHON_INCLUDE_DIR:PATH=/Users/svExternals/install/python-3.9.10/include/python3.9
PYTHON_LIBRARY:FILEPATH=/Users//svExternals/install/python-3.9.10/lib/libpython3.9.dylib
```

Note that the svExternals Qt5 can't be found using `find_package()`, have to set `CMAKE_PREFIX_PATH`.

**Comment by ktbolt** [comment]
My test program 
```
#include "mitkProperties.h"

int main()
{
  MITK_INFO << "Goodbye world!";
  return 0;
}
```
built with svExternals exits with a `Segmentation fault: 11`.

Crash log
```
Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libMitkCore.dylib             	       0x119302b20 itk::ObjectFactoryBase::UnRegisterFactory(itk::ObjectFactoryBase*) + 48
1   libMitkPlanarFigureIO.dylib   	       0x12ab6b461 mitk::PlanarSubdivisionPolygonSerializerRegistrationMethod::~PlanarSubdivisionPolygonSerializerRegistrationMethod() + 33 (mitkPlanarFigureSubclassesSerializer.cpp:51)
2   libMitkPlanarFigureIO.dylib   	       0x12ab5db05 mitk::PlanarSubdivisionPolygonSerializerRegistrationMethod::~PlanarSubdivisionPolygonSerializerRegistrationMethod() + 21 (mitkPlanarFigureSubclassesSerializer.cpp:51)
3   libsystem_c.dylib             	    0x7ff8062d1dd4 __cxa_finalize_ranges + 409
4   libsystem_c.dylib             	    0x7ff8062d1bee exit + 35
```

**Comment by lucapegolotti** [comment]
@ktbolt Weird. I noticed that there are some changes related to PlaneGeometry in the [patch](https://github.com/SimVascular/svExternals/blob/main/patches/mitk-2022.10.patch) I made for MITK. I honestly don’t remember why I needed these fixes though…

**Comment by ktbolt** [comment]
@lucapegolotti I will remove the patches so I can figure out what they are for. 

I will then add comments to the function where a patch is made to document what the the patch does and why it was needed. At some point the patch may no longer be needed.

**Comment by ktbolt** [comment]
I've fixed the segfault in the Segmentation Tool
<img width="1744" alt="Screen Shot 2024-04-03 at 1 24 42 PM" src="https://github.com/SimVascular/SimVascular/assets/23109458/39c80c46-3db9-4701-ad00-b05da69eb347">

The problem was in the copy construction `mitk::SlicedGeometry3D::SlicedGeometry3D(const SlicedGeometry3D &other)`. The fix was to replace
```
PlaneGeometry *geometry2D = other.m_PlaneGeometries[s]->Clone();
```
with
```
mitk::PlaneGeometry::Pointer geometry2D = other.m_PlaneGeometries[s]->Clone();
```
Note that there is no test in MITK/Modules/Core/test for unevenly spaced slices so it might be that this operation is not very well supported.

The next task is to get the image slices to appear in the MITK graphics windows.

**Comment by lucapegolotti** [comment]
Amazing!

**Comment by ktbolt** [comment]
I'm making some progress, able to see a slice in the various windows
<img width="1744" alt="Screen Shot 2024-04-04 at 1 38 40 PM" src="https://github.com/SimVascular/SimVascular/assets/23109458/cb32a32d-700b-4fa8-8663-ee2654d1e3f9">

A couple of issues
- The 2D slice in the 3D window is an image plane and not a bounded plane
- The potential view is not displaying image intensity gradient

The code is essentially undocumented by the original developers so it is not clear at all what all is going on, for example what is all of this about
```
currentDataNode->SetBoolProperty( "in plane resample extent by geometry", mitk::BoolProperty::New( true ),intensityWindow->GetRenderer());
           
intensityWindow->GetRenderer()->GetCurrentWorldPlaneGeometryNode()->SetBoolProperty( "in plane resample size by geometry",
        mitk::BoolProperty::New( true ),m_renderWindow->GetQmitkRenderWindow("coronal")->GetRenderer());
```

Just a few minutes spent documented the code would save us hours of trying to figure out what is going on.

**Comment by ktbolt** [comment]
The functionality I was trying to figure out in MITK, ITK or VTK (e.g. `currentDataNode->SetBoolProperty("show gradient", true, potentialWindow->GetRenderer())`) was actually custom SV code added to the MITK source using an SV patch file. These patches are not included in the current svExternals MITK patch file. 

I manually added the patch code and modified the `MITK-2022.10/Modules/Core/CMakeLists.txt` file to add the VTK `ImagingGeneral` and `ImagingStatistics modules`.

Now the 2D slice appears in the 3D window and the image gradient is shown. However, the 2D image slice does not fit the plane slice and 2D image windows.
<img width="1629" alt="Screen Shot 2024-04-05 at 6 33 00 PM" src="https://github.com/SimVascular/SimVascular/assets/23109458/19e544f6-3d14-4963-be32-bef53aafe279">

Note that the 1600 line SV MITK patch file `Externals/Patches/2018.05/patch-mitk-2018.04.patch` contains  no comments describing the purpose of the patched code, if it is to fix a compatibility problem or for new functionality.

**Comment by ktbolt** [comment]
I fixed some of the patch code and now the 2D slices now look correct.
 
<img width="1629" alt="Screen Shot 2024-04-09 at 2 55 42 PM" src="https://github.com/SimVascular/SimVascular/assets/23109458/7bee5158-e775-4606-bd07-33f39972daac">

**Comment by ktbolt** [comment]
I've modified `mitk::SlicedGeometry3D::SetPlaneGeometry` from 
```
PlaneGeometry *geometry2D = other.m_PlaneGeometries[s]->Clone();
```
to
```
mitk::PlaneGeometry::Pointer geometry2D = other.m_PlaneGeometries[s]->Clone();
```

The Segmentation Tool now works for some segmentation methods

<img width="1436" alt="Image" src="https://github.com/user-attachments/assets/879a7b2b-64bd-4c21-9d94-6ba6d2994312" />

**Comment by ktbolt** [comment]
Segmentation using `LevelSet` fails with
```
SimVascular/Code/Source/sv3/ITKSegmentation/sv3_VascularLevelSetImageFilter.h:78:
ITK ERROR: VascularPhaseTwoLevelSetImageFilter(0x11ed16a60): No finite difference function was specified.
```

Lots of the LevelSet code in `SimVascular/Code/Source/sv3/ITKSegmentation` has been commented out leaving incomplete definitions to some template functions. This appears to have been done because of conflicts with the latest ITK.

**Comment by ktbolt** [comment]
I've fixed the ramianing ITK incompatibilities but I am getting this when using level sets

<img width="532" alt="Image" src="https://github.com/user-attachments/assets/6bd6ac2f-f1b8-4d81-8df3-30fc35b7576c" />

It's difficult to follow what has been commented out in the `ITKSegmentation` code, seems that I missed something, so I will start over with the conversion from the original SV code.

**Comment by ktbolt** [comment]
I'm working on getting the Segmentation Tool `Machine Learning` segmentation working.

I needed to fix  `Python/site-packages/sv/meshsim_options.py` (from collections.abc import)  and add the `PyYAML` package to the svExternals Python build/install. 

Selecting `Machine Learning` segmentation loads the Python scripts OK but then SV crashes 
```
imported svWrapper.py
importing seg_reg modules
./sv: line 150: 86152 Abort trap: 6           $sv_exe $*
```

Note that the **installed SV also crashes when using Machine Learning segmentation**
```
imported svWrapper.py
importing seg_reg modules
importing factories
/Applications/SimVascular.app/Contents/Resources/simvascular: line 128: 86255 Abort trap: 6           ${svexe} $*
```

**Comment by ktbolt** [comment]
The failure occurs when importing vtk from `vascular_data.py`
```
import vtk
```

Another issue is that the `tensorflow` Python package needed by SV machine learning is supported on MacOS for Python 3.9–3.11.

**Comment by ktbolt** [comment]
I've re-built svExternals using Python 3.11 and VTK now loads no problem.

The machine learning Python code in `SimVascular/Python/site-packages/sv_ml` still crashes, problems with Python package versions and such but the biggest problem I think is using out-of-date TensorFlow operations.

The best thing to do here is to **replace TensorFlow with PyTorch**.

@numisveinsson We spoke about doing this conversion some time ago, have you had a look at this ?

**Comment by ktbolt** [comment]
All of the Segmentation Tool operations except for the Machine Learning segmentation seem to work ok. 

I've been trying to modify the MITK code according to the old SV patch files to 

1) Show a 2D image gradient 

2) Display a bounded 2D slice in the 3D view.

The new MITK code has changed some and there are methods that no longer exist so there is a bit of guess work to figure out what the patch code is doing.

**Comment by ktbolt** [comment]
I've manually modified the MITK 2024 code using the old SV `patch-mitk-2018.04.2-2019-06-11.patch` file  and the MITK 2018 version as a guide. 

The display of the  bounded 2D slice in the 3D view seems to work now

<img width="1352" alt="Image" src="https://github.com/user-attachments/assets/61697227-4fcc-4a92-8fed-bc5f51ddc68c" />

**Comment by ktbolt** [comment]
I've added the 2D image gradient code to MITK from `patch-mitk-2018.04.2-2019-06-11.patch` but the image does not look correct

<img width="595" alt="Image" src="https://github.com/user-attachments/assets/a5ae9d09-991b-424e-96fa-4bae9ce193da" />

I've tested the VTK `vtkImageGradientMagnitude` class in a separate program and it works fine so I don't think this is a VTK problem.

**Comment by ktbolt** [comment]
The 2D image gradient is now working

<img width="545" alt="Image" src="https://github.com/user-attachments/assets/23bea810-b500-4b2b-bb9d-ef83885f9b10" />

missed some patch code and incorrectly added some code to the `mitk::ImageVtkMapper2D::GenerateDataForRenderer` function.
